---
title: "Cox_Trans"
author: "Yuying Lu"
date: "2024-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message=FALSE,dpi=600)
```


```{r}
library(tidyr)
library(dplyr)
library(ape)
library(survival)
library(prodlim)
library(pec)
library(forestmodel)
library(survminer)
library(Hmisc)
library(MASS)
library(Matrix)
library(glmnet)
library(rootSolve)
library(ggplot2)
library(cowplot)
library(rms)
library(cowplot)
library(riskRegression)
library(survex)

source('Generate_data.R')
source('use.R')
source('R/Hazard_beta.R')
source('R/Hazard_pred.R')
source('R/surv_pred.R')
source('R/Cox_TL.R')
source('R/Cox_TL_CV.R')
source('R/Log_lik_wei.R')
source('R/Cox_CV.R')
source('R/Cox_CV_vali.R')
library(reticulate)
library(TransCox)
use_python("/n/home09/lyy/.pyenv/versions/3.9.19/bin/python")
tc<-import('TransCoxFunction')
tfp<-tc$tfp
np<-tc$np
tf<-tc$tf
TransCox<-tc$TransCox

```


```{r}
set.seed(88)
N<-20000
Ns<-4000
Nt<-200
nt<-200 #for test
Ng_t<-5000
nu<-Nt/Ns
kt<-4
ks<-1/2
ratio_scale<-0
p<-10
Nsim <-100

for (setting in c(1)) {
  file_name<-paste0('result_12.24/result_(setting=',setting,',p=',p,',eta=',ratio_scale,').csv')
  re<-c()
  for(ti in 1:Nsim){  
    sim<-Gen_X_dif(N,Ns,Nt+nt+Ng_t,setting,kt,ks,ratio_scale,p)
    data_test<-sim$data_t[(Nt+1):(Nt+nt),]
    data_test$R<-as.factor(rep(0,nt))
    data_orac<-sim$data_t[(Nt+nt+1):(Nt+nt+Ng_t),]
    data_orac$R<-as.factor(rep(0,Ng_t))
    data_vali <- data_orac[1:(Nt/2),]
    data_both<-rbind(sim$data_s,sim$data_t[1:Nt,])
    data_both$R<-as.factor(c(rep(1,Ns),rep(0,Nt)))
    data_s<-data_both[1:Ns,]
    data_t<-data_both[(Ns+1):(Nt+Ns),]
    
    summary(data_t)
    #data_both%>%ggplot(aes(x=X1,y=X2,color=R))+geom_point(size=0.5,alpha=0.5)
    
    nu<-Nt/Ns
    X_s<-as.matrix(data_s[1:Ns,1:p])
    X_t<-as.matrix(data_t[1:Nt,1:p])
    X_test<-as.matrix(data_test[,1:p])
     
    
    cov<-colnames(data_t)[1:p]
    functext = paste0("cox_orac<- rms::cph(survival::Surv(time, status) ~ ", paste(cov, collapse = "+"), ", 
                      data = data_orac,x=TRUE,y=TRUE,surv=TRUE)")
    eval(parse(text = functext))
    
    functext = paste0("cox_t<- rms::cph(survival::Surv(time, status) ~ ", paste(cov, collapse = "+"), ", 
                      data = data_t,x=TRUE,y=TRUE,surv=TRUE)")
    eval(parse(text = functext))
    
    functext = paste0("cox_s<- rms::cph(survival::Surv(time, status) ~ ", paste(cov, collapse = "+"), ", 
                      data = data_s,x=TRUE,y=TRUE,surv=TRUE)")
    eval(parse(text = functext))
    
    functext = paste0("cox_str<- rms::cph(survival::Surv(time, status) ~ ", paste(c(cov,'strat(R)'), collapse = "+"), ", 
                      data = data_both,x=TRUE,y=TRUE,surv=TRUE)")
    eval(parse(text = functext))
    
    theta_ini<-rep(0,p+1)
    Xs_new<-as.matrix(cbind(rep(1,Ns),X_s))
    Xt_new<-as.matrix(cbind(rep(1,Nt),X_t))
    
    w_opt <- nlm(opt_w_l2(Xs_new,Xt_new,1), theta_ini, iterlim = 500)
    theta<-w_opt$estimate
    wei_ts_l2<-exp(Xs_new%*%matrix(theta,ncol=1))
    #wei_true<-exp(-X_s[,3]*ratio_scale)
    cox_cv_l2<-Cox_CV(data_t,data_s,weights=wei_ts_l2,p)
    
    
    cov<-colnames(data_t)[1:p]
    pData<-data_t%>%mutate(status=status+1)
    aData<-data_s%>%mutate(status=status+1)
    
    Cout <- GetAuxSurv(aData, cov = cov)
    Pout <- GetPrimaryParam(pData, q = Cout$q, estR = Cout$estR)
    
    LRres <- SelLR_By_BIC(primData = pData,
                 auxData = aData,
                 cov = cov ,
                 statusvar = "status", lambda1 = 0.01, lambda2 = 0.01,
                 learning_rate_vec = c(0.0001, 0.0002,0.0005),
                 nsteps_vec = c(200,400,800))
    
    BICres <- SelParam_By_BIC(primData = pData,
                    auxData = aData,
                    cov = cov ,
                    statusvar = "status",
                    lambda1_vec = c(0.01, 0.05, seq(0.1, 1, by = 0.1)),
                    lambda2_vec = c(0.01, 0.05, seq(0.1, 1, by = 0.1)),
                    learning_rate = LRres$best_lr, nsteps = LRres$best_nsteps)
    
    
    Tres <- runTransCox_one(Pout, l1 = BICres$best_la1, l2 = BICres$best_la2, 
                            learning_rate = LRres$best_lr, 
                            nsteps = LRres$best_nsteps, cov = cov )
    
    time_test<-seq(0,1.5,0.01)
    surv_orac<-predictSurvProb(cox_orac,newdata=data_test,times=time_test)
    surv_t<-predictSurvProb(cox_t,newdata=data_test,times=time_test)
    surv_s<-predictSurvProb(cox_s,newdata=data_test,times=time_test)
    surv_str<-predictSurvProb(cox_str,newdata=data_test,times=time_test)
    surv_trans<-t(apply(X_test,1,function(x)surv_pred(Tres$time,cumsum(Tres$new_IntH),Tres$new_beta,x,time_test)$pred))
    surv_cv_l2<-predictSurvProb(cox_cv_l2,newdata=data_test,times=time_test)
    
    surv_test<-Surv(data_test$time,data_test$status)
    
    Method<-c('Cox_Orac', 'Cox_T', 'Cox_S', 'Cox_Str','TransCox','Cox_TL_l2')
    beta_est<-rbind(coef(cox_orac),coef(cox_t),coef(cox_s),coef(cox_str),Tres$new_beta,coef(cox_cv_l2))
    
    rownames(beta_est)<-Method
    
    rcorr.cens(exp(X_test%*%coef(cox_t)),Surv(data_test$time,data_test$status))['C Index']
    
    C_index<-apply(beta_est,1,function(x){1-rcorr.cens(exp(X_test%*%x),Surv(data_test$time,data_test$status))['C Index']})
    
    IBS<-c(integrated_brier_score(surv_test, surv = surv_orac, times = time_test),
           integrated_brier_score(surv_test, surv = surv_t, times = time_test),
           integrated_brier_score(surv_test, surv = surv_s, times = time_test),
           integrated_brier_score(surv_test, surv = surv_str, times = time_test),
           integrated_brier_score(surv_test, surv = surv_trans, times = time_test),
           integrated_brier_score(surv_test, surv = surv_cv_l2, times = time_test))
    
    re_new<-cbind(Method=Method,data.frame(C_index=C_index,IBS=IBS,p=paste0('p=',p),Setting=setting),eta=ratio_scale)
    re<-rbind(re,re_new)
    write.csv(re,file_name,row.names = F)
    }
}
re
re%>%
  mutate(Method=factor(Method,levels=c('Cox_Orac','Cox_T','Cox_S','Cox_Str','TransCox','Cox_TL_l2'))) %>% 
  group_by(Setting,p,Method)%>%summarize_each(funs(mean))
```



```{r}
N<-20000
Ns<-4000
Nt<-200
nt<-200 #for test
Ng_t<-5000
nu<-Nt/Ns
kt<-4
ks<-1/2
ratio_scale<-0
re<-c()
Nsim <- 100
for (p in c(10,20)) {
  for (setting in 1:4) {
    file_name<-paste0('result_10.13/result_(setting=',setting,',p=',p,',eta=',ratio_scale,').csv')
    re<-c()
    for(ti in 1:Nsim){  
      sim<-Gen_X_dif(N,Ns,Nt+nt+Ng_t,setting,kt,ks,ratio_scale,p)
      data_test<-sim$data_t[(Nt+1):(Nt+nt),]
      data_test$R<-as.factor(rep(0,nt))
      data_orac<-sim$data_t[(Nt+nt+1):(Nt+nt+Ng_t),]
      data_orac$R<-as.factor(rep(0,Ng_t))
      data_vali <- data_orac[1:(Nt/2),]
      data_both<-rbind(sim$data_s,sim$data_t[1:Nt,])
      data_both$R<-as.factor(c(rep(1,Ns),rep(0,Nt)))
      data_s<-data_both[1:Ns,]
      data_t<-data_both[(Ns+1):(Nt+Ns),]
      
      summary(data_t)
      #data_both%>%ggplot(aes(x=X1,y=X2,color=R))+geom_point(size=0.5,alpha=0.5)
      
      nu<-Nt/Ns
      X_s<-as.matrix(data_s[1:Ns,1:p])
      X_t<-as.matrix(data_t[1:Nt,1:p])
      X_test<-as.matrix(data_test[,1:p])
       
      
      cov<-colnames(data_t)[1:p]
      functext = paste0("cox_orac<- rms::cph(survival::Surv(time, status) ~ ", paste(cov, collapse = "+"), ", 
                        data = data_orac,x=TRUE,y=TRUE,surv=TRUE)")
      eval(parse(text = functext))
      
      functext = paste0("cox_t<- rms::cph(survival::Surv(time, status) ~ ", paste(cov, collapse = "+"), ", 
                        data = data_t,x=TRUE,y=TRUE,surv=TRUE)")
      eval(parse(text = functext))
      
      functext = paste0("cox_s<- rms::cph(survival::Surv(time, status) ~ ", paste(cov, collapse = "+"), ", 
                        data = data_s,x=TRUE,y=TRUE,surv=TRUE)")
      eval(parse(text = functext))
      
      functext = paste0("cox_str<- rms::cph(survival::Surv(time, status) ~ ", paste(c(cov,'strat(R)'), collapse = "+"), ", 
                        data = data_both,x=TRUE,y=TRUE,surv=TRUE)")
      eval(parse(text = functext))
      
      theta_ini<-rep(0,p+1)
      Xs_new<-as.matrix(cbind(rep(1,Ns),X_s))
      Xt_new<-as.matrix(cbind(rep(1,Nt),X_t))
      w<-multiroot(f=model_w(Xs_new,Xt_new),start=theta_ini)
      theta<-w$root
      wei_ts<-exp(Xs_new%*%matrix(theta,ncol=1))
      #wei_true<-exp(-X_s[,3]*ratio_scale)
      cox_cv<-Cox_CV(data_t,data_s,weights=wei_ts,p)
      
      
      #functext = paste0("cox_tlw<- rms::cph(survival::Surv(time, status) ~ ", paste(c(cov,'strat(R)'), collapse = "+"), ", 
                        #data = data_both,weights=c(nu*wei_true,rep(1,Nt)),x=TRUE,y=TRUE,surv=TRUE)")
      #eval(parse(text = functext))
      
      
      time_test<-seq(0,1.5,0.01)
      surv_orac<-predictSurvProb(cox_orac,newdata=data_test,times=time_test)
      surv_t<-predictSurvProb(cox_t,newdata=data_test,times=time_test)
      surv_s<-predictSurvProb(cox_s,newdata=data_test,times=time_test)
      surv_str<-predictSurvProb(cox_str,newdata=data_test,times=time_test)
      surv_cv<-predictSurvProb(cox_cv,newdata=data_test,times=time_test)
      
      surv_test<-Surv(data_test$time,data_test$status)
      
      Method<-c('Cox_Orac', 'Cox_T', 'Cox_S', 'Cox_Str', 'Cox_CV')
      beta_est<-rbind(coef(cox_orac),coef(cox_t),coef(cox_s),coef(cox_str),coef(cox_cv))
      
      rownames(beta_est)<-Method
      
      C_index<-apply(beta_est,1,function(x){1-rcorr.cens(exp(X_test%*%x),Surv(data_test$time,data_test$status))['C Index']})
      
      IBS<-c(integrated_brier_score(surv_test, surv = surv_orac, times = time_test),
             integrated_brier_score(surv_test, surv = surv_t, times = time_test),
             integrated_brier_score(surv_test, surv = surv_s, times = time_test),
             integrated_brier_score(surv_test, surv = surv_str, times = time_test),
             integrated_brier_score(surv_test, surv = surv_cv, times = time_test))
      
      re_new<-cbind(Method=Method,data.frame(C_index=C_index,IBS=IBS,p=paste0('p=',p),Setting=setting),eta=ratio_scale)
      re<-rbind(re,re_new)
      write.csv(re,file_name,row.names = F)
      }
  }
}
re
```





```{r,fig.width=15,fig.height=12}

data_re<-re%>%mutate(Method=factor(Method,levels=c('Cox_Orac','Cox_T','Cox_Str','Cox_CV')))

data_long<-gather(data=data_re,key="Index",value="Value",C_index:IBS)

summary_data<-data_re%>%
  group_by(Setting,Method)%>%summarize_each(funs(mean))
#cbind(summary_data[,1:3],round(summary_data[,7:8],4))



size_axis<-20

plot3<-data_long%>%
  ggplot(aes(x=Method,y=Value,fill=Method))+
  geom_boxplot(outlier.size =0.3)+
  scale_fill_brewer(type='seq')+
  facet_grid(Index~Setting,scales='free')+
  xlab(NULL)+
  ylab('IBS')+
  theme(axis.text.x = element_text(angle = 50, vjust = 1, hjust = 1, size =  size_axis),
        strip.text.x = element_text(size = size_axis-2),
        strip.text.y = element_text(size = size_axis-2),
        axis.title.y = element_text(size = size_axis),
        axis.text.y=element_text(size = size_axis),
        legend.text =element_text(size = size_axis-2),
        legend.title = element_text(size=size_axis),
        strip.switch.pad.grid = unit(1, "inch")) 

plot3


```
